server:
  port: 1112
eureka:
  instance:
    hostname: eureka-server-node2
  client:
    service-url:
      defaultZone: http://eureka-server-node1:1111/eureka/,http://eureka-server-node3:1113/eureka/


