server:
  port: 1111
eureka:
  instance:
    hostname: eureka-server-node1
  client:
    service-url:
      defaultZone: http://eureka-server-node2:1112/eureka/,http://eureka-server-node3:1113/eureka/


